# Generated by Django 4.2.2 on 2025-12-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BocetoApp', '0004_alter_post_options_alter_post_autor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('pais', models.CharField(choices=[('DE', '🇩🇪 Alemania'), ('FR', '🇫🇷 Francia'), ('IT', '🇮🇹 Italia'), ('ES', '🇪🇸 España'), ('NL', '🇳🇱 Países Bajos'), ('BE', '🇧🇪 Bélgica'), ('UK', '🇬🇧 Reino Unido'), ('US', '🇺🇸 Estados Unidos'), ('JP', '🇯🇵 Japón'), ('OTHER', '🌍 Otro')], max_length=10, verbose_name='País')),
                ('cantidad', models.CharField(max_length=100, verbose_name='Cantidad aproximada (cajas/semana)')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje adicional')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('atendida', models.BooleanField(default=False, verbose_name='¿Atendida?')),
            ],
            options={
                'verbose_name': 'cotización',
                'verbose_name_plural': 'cotizaciones',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('cargo', models.CharField(blank=True, max_length=200, verbose_name='Cargo')),
                ('testimonio', models.TextField(verbose_name='Testimonio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Calificación (1-5)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Mostrar en sitio?')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimoniales',
                'ordering': ['-created'],
            },
        ),
    ]
